### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by benmarwick** [tonydoss/UThwigl#14]
Tasks to complete: 

- [ ] to have results save to the disk (not sure how that's gonna work with Binder; same question for uses to load their own data in Binder) 

- [ ] have an app for csUTh(). 

- [x]  option for users to paste their data, instead of upload a csv.
